# Generated by Django 3.2.19 on 2023-06-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiless', '0002_auto_20230518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_ro9o74', upload_to='images/'),
        ),
    ]
